name: CI Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - dev

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        uses: wearerequired/lint-action@v2
        with:
          prettier: true

  build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
