name: CI Workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - dev

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install node.js dependencies
        run: npm ci

      - name: Run prettier
        uses: creyD/prettier_action@v4.2
        with:
          same_commit: true

      - name: Run eslint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

  build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
